### ISSUE TITLE
keyboard.valueText("foo") returns a &nbsp; and not a white space

### ISSUE THREAD

**Issue by meduzo** [AirConsole/airconsole-keyboard#1]
It's something that kept breaking my game, maybe it's not an issue itself, but it's helpful to point this out.

**Comment by meduzo** [comment]
The solution for this is to replace line 81:

`textarea.innerHTML = (this.valueHTML(input_id));`

with this:

`textarea.innerHTML = (this.valueHTML(input_id)).replace(/&nbsp;/gi, " ");`

it's a simple replace, but it works really good if you want your line breaks to work ;)

**Comment by andrin-n-dream** [comment]
This is on purpose. Use this.valueText instead or replace the space key in the keyboard with " " instead &nbsp;
